import type { StatusDomain } from "./statusMeta";

export const EXPLICIT_STATUS_LABELS: Record<string, string> = {
  mock: "模拟数据",
  fallback: "兜底数据",
  stale: "数据过期",
  unavailable: "不可用",
  manual_required: "需人工处理",
  not_connected: "未连接",
  not_required: "无需审查",
};

export const GENERIC_LABELS: Record<string, string> = {
  active: "运行中",
  api: "接口数据",
  approved: "已通过",
  available: "可用",
  cancelled: "已取消",
  clear: "清晰",
  complete: "完整",
  connected: "已连接",
  critical: "严重",
  danger: "风险",
  degraded: "降级",
  done: "完成",
  error: "错误",
  failed: "失败",
  final: "最终数据",
  generated: "已生成",
  idle: "空闲",
  info: "信息",
  live: "实时",
  mixed: "混合",
  neutral: "中性",
  not_configured: "未配置",
  ok: "正常",
  partial: "部分可用",
  partial_success: "部分成功",
  passed: "已通过",
  pending: "待处理",
  prelim: "初步数据",
  queued: "排队",
  queued_not_implemented: "已排队未执行",
  ready: "就绪",
  rejected: "已拒绝",
  rerun: "重跑",
  retrying: "重试中",
  review: "复核",
  running: "运行中",
  skipped: "已跳过",
  success: "成功",
  supported: "已支持",
  unknown: "未知",
  warn: "警告",
  warning: "警告",
};

export const DOMAIN_LABELS: Partial<Record<StatusDomain, Record<string, string>>> = {
  task: {
    cancelled: "已取消",
    clear: "CLEAR",
    degraded: "降级",
    done: "完成",
    failed: "失败",
    needs_review: "待复核",
    partial_success: "部分成功",
    pending: "待处理",
    queued: "待执行",
    retrying: "重试中",
    running: "运行中",
    skipped: "已跳过",
    success: "成功",
  },
  step: {
    done: "完成",
    error: "错误",
    failed: "失败",
    pending: "待处理",
    queued: "排队",
    running: "运行中",
  },
  review: {
    approved: "已通过",
    contradicted: "有冲突",
    conflicted: "有冲突",
    needs_review: "待复核",
    not_required: "无需审查",
    not_reviewed: "未审查",
    partial: "部分待补证",
    partially_supported: "部分支持",
    pending: "待复核",
    rejected: "已拒绝",
    rerun: "重跑",
    success: "已核验",
    supported: "已支持",
    unavailable: "审查不可用",
    unsupported: "不支持",
  },
  report: {
    missing: "缺失",
    pending: "待生成",
    ready: "就绪",
  },
  source: {
    api: "真实接口",
    artifact: "产物",
    asset: "资产",
    citations: "引用",
    confidence: "可信度",
    data_source: "数据源",
    fallback: "兜底数据",
    mock: "模拟数据",
    run_id: "运行编号",
    topic: "主题",
    trace: "溯源",
    type: "类型",
    unavailable: "不可用",
    updated_at: "更新时间",
  },
  agent: {
    complete: "完整",
    failed: "失败",
    partial: "部分可用",
    provisional: "临时",
    queued: "排队",
    running: "运行中",
    success: "成功",
    unavailable: "不可用",
  },
  event: {
    "中": "中",
    "低": "低",
    "传闻中": "传闻中",
    "利多黄金": "利多",
    "利空黄金": "利空",
    "发展中": "发展中",
    "地缘政治": "地缘政治",
    "已公布": "已公布",
    "已定价": "已定价",
    "已结束": "已结束",
    "市场事件": "市场事件",
    "未定价": "未定价",
    "混合": "混合",
    "经济数据": "经济数据",
    "货币政策": "货币政策",
    "贸易政策": "贸易政策",
    "部分定价": "部分定价",
    "高": "高",
  },
};

export const UP_STATUSES = new Set([
  "active",
  "api",
  "approved",
  "available",
  "complete",
  "connected",
  "done",
  "final",
  "generated",
  "live",
  "ok",
  "passed",
  "ready",
  "success",
  "supported",
  "利多黄金",
  "已公布",
  "已定价",
]);

export const WARN_STATUSES = new Set([
  "cancelled",
  "conflicted",
  "degraded",
  "fallback",
  "manual_required",
  "mock",
  "needs_review",
  "partial",
  "partial_success",
  "partially_supported",
  "prelim",
  "provisional",
  "stale",
  "warn",
  "warning",
  "中",
  "传闻中",
  "混合",
  "贸易政策",
  "部分定价",
]);

export const DOWN_STATUSES = new Set([
  "contradicted",
  "critical",
  "danger",
  "error",
  "failed",
  "missing",
  "rejected",
  "unsupported",
  "地缘政治",
  "利空黄金",
  "未定价",
  "高",
]);

export const INFO_STATUSES = new Set([
  "info",
  "queued",
  "queued_not_implemented",
  "rerun",
  "review",
  "retrying",
  "running",
  "发展中",
  "经济数据",
  "货币政策",
]);

export const DIM_STATUSES = new Set([
  "clear",
  "idle",
  "neutral",
  "not_configured",
  "not_reviewed",
  "pending",
  "skipped",
  "unknown",
  "unavailable",
  "低",
  "已结束",
  "市场事件",
]);
