"""Deterministic contracts and policy engines for the XAUUSD decision chain."""

from apps.analysis.gold_policy.consistency_policy import evaluate_analysis_strategy_consistency
from apps.analysis.gold_policy.consistency_schemas import (
    AnalysisStrategyConsistencyDecision,
    AnalysisStrategyConsistencyInput,
    ConsistencyReasonCode,
    ConsistencyStatus,
    StrategyChangeKind,
    build_analysis_strategy_consistency_decision,
)
from apps.analysis.gold_policy.daily_close_delivery import (
    GoldDailyCloseContextBundle,
    GoldDailyCloseDeliveryArtifacts,
    GoldDailyCloseFinalReport,
    GoldDailyCloseStrategyDiff,
    GoldDailyCloseTokenTrace,
    build_gold_daily_close_delivery,
)
from apps.analysis.gold_policy.daily_close_loop import evaluate_gold_daily_close_loop
from apps.analysis.gold_policy.daily_close_schemas import (
    CanonicalCommitAction,
    DailyCloseLoopInput,
    DailyCloseLoopReason,
    DailyCloseLoopResult,
    build_daily_close_loop_result,
)
from apps.analysis.gold_policy.daily_close_runtime import (
    GoldDailyCloseRuntimeControls,
    GoldDailyCloseRuntimeExecution,
    execute_gold_daily_close_runtime,
)
from apps.analysis.gold_policy.daily_close_store import (
    DailyCloseBundleWriteResult,
    DailyCloseCanonicalHead,
    DailyCloseCanonicalReceipt,
    DailyCloseHeadConflictError,
    DailyCloseHeadLookup,
    DailyCloseStoreError,
    load_gold_daily_close_head,
    persist_gold_daily_close_run,
)

from apps.analysis.gold_policy.analysis_policy import (
    GoldAnalysisDecision,
    PolicyDriver,
    evaluate_gold_analysis_policy,
)
from apps.analysis.gold_policy.attribution_policy import (
    AttributionDriver,
    GoldPriceAttribution,
    attribute_gold_price,
)
from apps.analysis.gold_policy.feature_adapter import build_feature_snapshot_from_analysis_snapshot
from apps.analysis.gold_policy.feature_store import (
    PreviousFeatureSnapshotLookup,
    load_previous_feature_snapshot,
)
from apps.analysis.gold_policy.key_level_policy import (
    KeyLevelLifecycleResult,
    evaluate_key_level_lifecycle,
)
from apps.analysis.gold_policy.key_level_schemas import (
    KeyLevelAuthorityStatus,
    KeyLevelCalculationMethod,
    KeyLevelComparator,
    KeyLevelEvent,
    KeyLevelEventType,
    KeyLevelEvidence,
    KeyLevelEvidenceFactor,
    KeyLevelEvidenceTimeframe,
    KeyLevelKind,
    KeyLevelLifecycle,
    KeyLevelLifecycleDecision,
    KeyLevelPublicationStatus,
    KeyLevelPriceFact,
    KeyLevelQualificationClass,
    KeyLevelQualificationReceipt,
    KeyLevelReadModel,
    KeyLevelRetirementRule,
    KeyLevelRole,
    KeyLevelRuleCode,
    KeyLevelRuleSet,
    KeyLevelSourceInstrument,
    KeyLevelSourceRole,
    KeyLevelSpec,
    KeyLevelTransitionAction,
    build_key_level_event,
    build_key_level_lifecycle_decision,
    build_key_level_spec,
    key_level_strategy_eligible_at,
)
from apps.analysis.gold_policy.feature_snapshot import build_feature_snapshot
from apps.analysis.gold_policy.runtime_inputs import (
    GoldPolicyRuntimeInputs,
    prepare_gold_policy_runtime_inputs,
)
from apps.analysis.gold_policy.schemas import FeatureSnapshot, FeatureSnapshotInput
from apps.analysis.gold_policy.state_schemas import (
    AnalysisStage,
    AnalysisState,
    EvidenceCategory,
    EvidenceDeltaKind,
    EvidenceScope,
    HardInvalidationRule,
    MajorConfirmationRule,
    PendingRule,
    PendingTransition,
    StateTransitionPolicyDecision,
    TransitionAction,
    TransitionEvidence,
    build_analysis_state,
    build_state_transition_policy_decision,
)
from apps.analysis.gold_policy.state_transition_policy import (
    AnalysisStateTransitionResult,
    evaluate_analysis_state_transition,
    ordinary_stage_distance,
)
from apps.analysis.gold_policy.strategy_policy import evaluate_gold_strategy_policy
from apps.analysis.gold_policy.strategy_schemas import (
    EventRiskStatus,
    NoTradeReasonCode,
    OptionsRegime,
    ReleaseConditionCode,
    ReviewTriggerCode,
    StrategyDecision,
    StrategyDirection,
    StrategyEventRiskSnapshot,
    StrategyLevelReference,
    StrategyOptionsRegimeSnapshot,
    StrategyPolicyInput,
    StrategyStatus,
    build_strategy_decision,
    build_strategy_event_risk,
    build_strategy_options_regime,
)

__all__ = [
    "AnalysisStrategyConsistencyDecision",
    "AnalysisStrategyConsistencyInput",
    "AttributionDriver",
    "AnalysisStage",
    "AnalysisState",
    "AnalysisStateTransitionResult",
    "CanonicalCommitAction",
    "ConsistencyReasonCode",
    "ConsistencyStatus",
    "DailyCloseLoopInput",
    "DailyCloseLoopReason",
    "DailyCloseLoopResult",
    "DailyCloseBundleWriteResult",
    "DailyCloseCanonicalHead",
    "DailyCloseCanonicalReceipt",
    "DailyCloseHeadConflictError",
    "DailyCloseHeadLookup",
    "DailyCloseStoreError",
    "EvidenceCategory",
    "EvidenceDeltaKind",
    "EvidenceScope",
    "EventRiskStatus",
    "FeatureSnapshot",
    "FeatureSnapshotInput",
    "GoldAnalysisDecision",
    "GoldDailyCloseRuntimeControls",
    "GoldDailyCloseRuntimeExecution",
    "GoldDailyCloseContextBundle",
    "GoldDailyCloseDeliveryArtifacts",
    "GoldDailyCloseFinalReport",
    "GoldDailyCloseStrategyDiff",
    "GoldDailyCloseTokenTrace",
    "GoldPriceAttribution",
    "GoldPolicyRuntimeInputs",
    "HardInvalidationRule",
    "KeyLevelAuthorityStatus",
    "KeyLevelCalculationMethod",
    "KeyLevelComparator",
    "KeyLevelEvent",
    "KeyLevelEventType",
    "KeyLevelEvidence",
    "KeyLevelEvidenceFactor",
    "KeyLevelEvidenceTimeframe",
    "KeyLevelKind",
    "KeyLevelLifecycle",
    "KeyLevelLifecycleDecision",
    "KeyLevelLifecycleResult",
    "KeyLevelPublicationStatus",
    "KeyLevelPriceFact",
    "KeyLevelQualificationClass",
    "KeyLevelQualificationReceipt",
    "KeyLevelReadModel",
    "KeyLevelRetirementRule",
    "KeyLevelRole",
    "KeyLevelRuleCode",
    "KeyLevelRuleSet",
    "KeyLevelSourceInstrument",
    "KeyLevelSourceRole",
    "KeyLevelSpec",
    "KeyLevelTransitionAction",
    "MajorConfirmationRule",
    "NoTradeReasonCode",
    "OptionsRegime",
    "PendingRule",
    "PendingTransition",
    "PolicyDriver",
    "PreviousFeatureSnapshotLookup",
    "ReleaseConditionCode",
    "ReviewTriggerCode",
    "StrategyDecision",
    "StrategyDirection",
    "StrategyEventRiskSnapshot",
    "StrategyLevelReference",
    "StrategyOptionsRegimeSnapshot",
    "StrategyPolicyInput",
    "StrategyStatus",
    "StrategyChangeKind",
    "StateTransitionPolicyDecision",
    "TransitionAction",
    "TransitionEvidence",
    "attribute_gold_price",
    "build_feature_snapshot",
    "build_feature_snapshot_from_analysis_snapshot",
    "build_analysis_state",
    "build_analysis_strategy_consistency_decision",
    "build_daily_close_loop_result",
    "build_gold_daily_close_delivery",
    "build_key_level_event",
    "build_key_level_lifecycle_decision",
    "build_key_level_spec",
    "evaluate_analysis_state_transition",
    "evaluate_analysis_strategy_consistency",
    "build_state_transition_policy_decision",
    "build_strategy_decision",
    "build_strategy_event_risk",
    "build_strategy_options_regime",
    "evaluate_gold_analysis_policy",
    "evaluate_gold_daily_close_loop",
    "execute_gold_daily_close_runtime",
    "evaluate_key_level_lifecycle",
    "evaluate_gold_strategy_policy",
    "key_level_strategy_eligible_at",
    "load_previous_feature_snapshot",
    "load_gold_daily_close_head",
    "ordinary_stage_distance",
    "prepare_gold_policy_runtime_inputs",
    "persist_gold_daily_close_run",
]
