from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))
GOLD_CONTRACT_PATH = PROJECT_ROOT / "apps/frontend-web/src/generated/gold-contract.ts"


def _ts_const(name: str, values: tuple[str, ...]) -> str:
    rows = "\n".join(f'  "{value}",' for value in values)
    return f"export const {name} = [\n{rows}\n] as const;"


def render_gold_contract() -> str:
    from apps.contracts.gold import (
        GOLD_MAINLINE_IDS,
        GOLD_TRANSMISSION_CHAIN_IDS,
        GOLD_TRANSMISSION_PATH_IDS,
    )

    return "\n".join(
        [
            "// Generated by scripts/generate_frontend_contracts.py. Do not edit manually.",
            "",
            _ts_const("GOLD_MAINLINE_IDS", GOLD_MAINLINE_IDS),
            "export type GoldMainline = (typeof GOLD_MAINLINE_IDS)[number];",
            "",
            _ts_const("GOLD_TRANSMISSION_CHAIN_IDS", GOLD_TRANSMISSION_CHAIN_IDS),
            "export type TransmissionChain = (typeof GOLD_TRANSMISSION_CHAIN_IDS)[number];",
            "",
            _ts_const("GOLD_TRANSMISSION_PATH_IDS", GOLD_TRANSMISSION_PATH_IDS),
            "export type TransmissionPath = (typeof GOLD_TRANSMISSION_PATH_IDS)[number];",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    expected = render_gold_contract()
    if args.check:
        actual = GOLD_CONTRACT_PATH.read_text(encoding="utf-8") if GOLD_CONTRACT_PATH.exists() else ""
        if actual != expected:
            print(f"{GOLD_CONTRACT_PATH} is not up to date")
            return 1
        return 0

    GOLD_CONTRACT_PATH.parent.mkdir(parents=True, exist_ok=True)
    GOLD_CONTRACT_PATH.write_text(expected, encoding="utf-8")
    print(f"wrote {GOLD_CONTRACT_PATH.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
